"""Compiles a finished comic layout into a downloadable, multi-page PDF."""

import os
from datetime import datetime

from fpdf import FPDF

from app.config import EXPORTS_DIR, STATIC_DIR


def _add_panel_page(pdf: FPDF, panel: dict) -> None:
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.multi_cell(0, 10, panel["title"])
    pdf.ln(2)

    image_path = os.path.join(STATIC_DIR, panel["image_path"]) if panel["image_path"] else None
    if image_path and os.path.exists(image_path):
        page_width = pdf.w - 2 * pdf.l_margin
        pdf.image(image_path, x=pdf.l_margin, w=page_width, h=110)
        pdf.ln(4)

    pdf.set_font("Helvetica", "I", 11)
    pdf.multi_cell(0, 7, panel.get("scene_description", ""))
    pdf.ln(2)

    if panel.get("caption"):
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(90, 90, 90)
        pdf.multi_cell(0, 6, f"({panel['caption']})")
        pdf.set_text_color(0, 0, 0)
        pdf.ln(1)

    if panel.get("narration"):
        pdf.set_font("Helvetica", "", 12)
        pdf.multi_cell(0, 7, panel["narration"])


def save_pdf(layout: list[dict], comic_title: str = "My ComicCraft Story") -> str:
    """Compile the full comic into a PDF and return the saved file's path
    (relative to static/, e.g. "exports/comic_20250101_120000.pdf").
    """
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.add_page()
    pdf.set_font("Helvetica", "B", 24)
    pdf.ln(60)
    pdf.multi_cell(0, 14, comic_title, align="C")
    pdf.set_font("Helvetica", "", 12)
    pdf.ln(4)
    pdf.multi_cell(0, 8, "Generated by ComicCraft", align="C")

    for panel in layout:
        _add_panel_page(pdf, panel)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"comic_{timestamp}.pdf"
    out_path = os.path.join(EXPORTS_DIR, filename)
    pdf.output(out_path)

    return f"exports/{filename}"
