"""Compiles a finished comic layout into a downloadable, multi-page PDF."""

import os
from datetime import datetime

from fpdf import FPDF

from app.config import EXPORTS_DIR, STATIC_DIR


def _register_unicode_font(pdf: FPDF) -> str:
    """Register an installed TrueType font that can encode generated text."""
    font_sets = [
        (
            os.path.join(os.environ.get("WINDIR", r"C:\Windows"), "Fonts"),
            "arial.ttf",
            "arialbd.ttf",
            "ariali.ttf",
        ),
        (
            "/usr/share/fonts/truetype/dejavu",
            "DejaVuSans.ttf",
            "DejaVuSans-Bold.ttf",
            "DejaVuSans-Oblique.ttf",
        ),
        (
            "/Library/Fonts",
            "Arial.ttf",
            "Arial Bold.ttf",
            "Arial Italic.ttf",
        ),
    ]
    for directory, regular, bold, italic in font_sets:
        font_paths = [os.path.join(directory, name) for name in (regular, bold, italic)]
        if all(os.path.isfile(path) for path in font_paths):
            for style, path in zip(("", "B", "I"), font_paths):
                pdf.add_font("ComicUnicode", style=style, fname=path)
            return "ComicUnicode"
    raise FileNotFoundError(
        "A Unicode TrueType font is required. Install Arial or DejaVu Sans to export PDFs."
    )


def _add_panel_page(pdf: FPDF, panel: dict) -> None:
    pdf.add_page()
    pdf.set_font("ComicUnicode", "B", 16)
    pdf.multi_cell(0, 10, panel["title"])
    pdf.ln(2)

    image_path = os.path.join(STATIC_DIR, panel["image_path"]) if panel["image_path"] else None
    if image_path and os.path.exists(image_path):
        image_width = 90
        pdf.image(image_path, x=(pdf.w - image_width) / 2, w=image_width)
        pdf.ln(4)

    pdf.set_font("ComicUnicode", "I", 11)
    pdf.multi_cell(0, 7, panel.get("scene_description", ""))
    pdf.ln(2)

    if panel.get("caption"):
        pdf.set_font("ComicUnicode", "", 10)
        pdf.set_text_color(90, 90, 90)
        pdf.multi_cell(0, 6, f"({panel['caption']})")
        pdf.set_text_color(0, 0, 0)
        pdf.ln(1)

    if panel.get("narration"):
        pdf.set_font("ComicUnicode", "", 12)
        pdf.multi_cell(0, 7, panel["narration"])


def save_pdf(layout: list[dict], comic_title: str = "My ComicCraft Story") -> str:
    """Compile the full comic into a PDF and return the saved file's path
    (relative to static/, e.g. "exports/comic_20250101_120000.pdf").
    """
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    _register_unicode_font(pdf)

    pdf.add_page()
    pdf.set_font("ComicUnicode", "B", 24)
    pdf.ln(60)
    pdf.multi_cell(0, 14, comic_title, align="C")
    pdf.set_font("ComicUnicode", "", 12)
    pdf.ln(4)
    pdf.multi_cell(0, 8, "Generated by ComicCraft", align="C")

    for panel in layout:
        _add_panel_page(pdf, panel)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"comic_{timestamp}.pdf"
    out_path = os.path.join(EXPORTS_DIR, filename)
    pdf.output(out_path)

    return f"exports/{filename}"
